services:
  backend:
    build: "./cloudleak_backend"
    env_file:
      - ".env"
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_BACKEND_CPUS:-0}"
          memory: "${DOCKER_BACKEND_MEMORY:-0}"
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - "redis:/data"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_REDIS_CPUS:-0}"
          memory: "${DOCKER_REDIS_MEMORY:-0}"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: cloudleak
      MONDODB_LOG_DIR: /dev/null

  frontend:
    build: "./cloudleak_frontend"
    ports:
      - 8080:80
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_FRONTEND_CPUS:-0}"
          memory: "${DOCKER_FRONTEND_MEMORY:-0}"
    depends_on:
      - backend
      - mongo

  worker:
    build:
      context: "./cloudleak_backend"
      target: "app"
    command: celery -A "cloudleak.app.celery_app" worker -l INFO
    depends_on:
      - redis
      - backend
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WORKER_CPUS:-0}"
          memory: "${DOCKER_WORKER_MEMORY:-0}"
    volumes:
      - "data:/data"
      - "db:/db"

volumes:
  redis: {}
  db: {}
  data: {}
